config/routes.rb
Wishlist::Application.routes.draw do

  resources :likes

  resources :admissions

  resources :activities

  match '/header_index', to: 'activities#header_index'

  use_link_thumbnailer

  namespace :plugin do
    match '/', to: 'lists#index'
    resources :lists
    resources :sessions
    resources :users

    match '/script', to: 'script#get'
    match '/widget', to: 'widget#index'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy'
    match '/signup', to: 'users#new'
  end

  match '/bookmarklet', to: 'items#bookmarklet'

  namespace :admin do
    resources :users, :items, :wishes, :comments
    match '/lptester', to: 'items#lptester'
  end

  resources :items, only: [:show, :new, :create, :update, :destroy, :inspiration] do
    resources :comments, :defaults => { :commentable => 'item' }
  end
  resources :wishes do
    collection { post :sort }
    resources :comments, :defaults => { :commentable => 'wish' }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reservations
  resources :vendors, only: [:index, :new, :create]
  resources :vendors, path: "v" , except: [:index, :new, :create]
  resources :password_resets

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match 'auth/:provider/callback', to: 'sessions#create_with_oauth'
  match 'auth/failure', to: redirect('/')

  root to: 'static_pages#home'
  get "sitemap.xml", to: "static_pages#sitemap", defaults: { format: "xml" }

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/privacy', to: 'static_pages#privacy'
  match '/terms',   to: 'static_pages#terms'
  match '/linkpreview', to: 'items#linkpreview'
  match '/inspiration', to: 'items#inspiration'
  match '/search',  to: 'static_pages#search'
  match 'contact_support', to: 'mailing#contact_support'

  match '/item_suggestion', to:'items#item_suggestion'
  match '/user_suggestion', to:'users#invite_suggestion'
  match '/vendor_suggestion', to:'vendors#invite_suggestion'

  match 'v/:id/edit_admins', to: 'vendors#edit_admins', as: 'edit_admins'

  match '/:id/update_password', to: 'users#update_password', as: 'update_password'
  match '/:id/update_notifications', to: 'users#update_notifications', as: 'update_notifications'

  resources :users, only: [:index, :new, :create]
  resources :users, path: "" , except: [:index, :new, :create] do
    resources :comments, :defaults => { :commentable => 'user' }
    resources :lists do
      post :share
    end
    member do
      get :following, :defaults => { :followed => 'user' }
      get :followers, :defaults => { :followed => 'user' }
    end
  end

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  private     :boolean          default(FALSE)
#  description :text
#

class List < ActiveRecord::Base
  attr_accessible :name, :description, :private

  belongs_to :user
  has_many :wishes, dependent: :destroy
  has_many :items, through: :wishes
  has_many :admissions, as: :accessible
  has_many :allowed_users, through: :admissions, source: :user

  accepts_nested_attributes_for :wishes, :items
  
  validates :name, presence: true, length: { maximum: 60 }
  validates :user_id, presence: true

  def self.allowed_for(current_user)
    if current_user
     #  allowed_users = "SELECT user_id FROM admissions WHERE (accessible_type = 'List' AND accessible_id IN (:admissions_list))"
    	# where("private = :false OR (private = :true AND :current_user IN (#{allowed_users})) OR (private = :true AND :current_user IN (user_id))", current_user: current_user.id, admissions_list: self.all.collect{|l| l.id}, false: false, true: true)
      lists = scoped.collect{|l| l if l.allowed_access(current_user) || l.private == false }.reject(&:nil?)
    else
      where("private = :false", false: false)
    end
  end

  def allowed_access(current_user)
    if self.user == current_user
      true
    elsif self.admissions.where(user_id: current_user.id).present?
      true
    else
      false
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :destroy]
  before_filter :correct_user,   only: [:update, :destroy]
  before_filter :allowed_user, only: [:show]
  include Analyzable

  respond_to :html, :json

  def index
    @user = User.find_by_slug!(params[:user_id])
    @lists = @user.lists
  end

  def show
    @wishes = @list.wishes.rank(:row_order)
    @lists = @user.lists.allowed_for(current_user)
    @message = Message.new
    tracker.track(mp_id, 'Visits list page', { list: @list.name, list_id: @list.id }) if mp_id
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.build(params[:list])
    if @list.save
      flash[:success] = "List created!"
      tracker.track(current_user.id, "Created a list")
      tracker.increment(current_user.id, {'Lists created' => 1})
      redirect_to [current_user, @list]
    else
      redirect_to current_user
    end
  end
  
  def update
    @list = List.find(params[:id])
    @list.update_attributes(params[:list])
    respond_to do |format|
      format.html { redirect_to [@list.user, @list] }
      format.json { render json: @list }
     end
  end

  def destroy
    @list.destroy
    tracker.track(current_user.id, "Removed a list")
    redirect_to :back
  end

  def share
    @list = List.find(params[:list_id])
    @message = Message.new(params[:message])
    
    if @message.valid?
      UserMailer.share_list(@message, @list.id).deliver
      tracker.track(current_user.id, "Shared a list")
      tracker.increment(current_user.id, {'Lists shared' => 1})
      redirect_to([@list.user, @list], :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
    end
  end


  private

    def correct_user
      @list = current_user.lists.find_by_id(params[:id])
      redirect_to current_user if @list.nil?
    end

    def allowed_user
      @user = User.find_by_slug!(params[:user_id])
      @list = @user.lists.find(params[:id])
      if @list.private?
        unless signed_in? && (@list.allowed_users.include?(current_user) || @list.user == current_user)
          redirect_to root_url
        end
      end
    end
end

app/controllers/plugin/lists_controller.rb
class Plugin::ListsController < ApplicationController

  include PluginHelper

  layout 'plugin'

  def index
    @wishes = get_wishes
    @list = List.new
  end

  def create
    @list = current_user.lists.build(params[:list])
    if @list.save
      save_wishes_to_list @list

      redirect_to plugin_list_path(@list)
    else
      redirect_to current_user
    end
  end

  def show
    @list = List.find params[:id]
  end

  def update
    @list = List.find params[:id]
    save_wishes_to_list @list

    redirect_to plugin_list_path(@list)
  end
end

app/views/lists/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :link %>
<%= f.text_field :link %>

<%= f.label :list_id %>
<%= f.collection_select :list_id, List.all, :id, :name %>

app/views/lists/_list-backup.html.erb
<% if current_page?(user_path(@user)) %> 
<!-- Profile lists -->
	<div class="span6">
		<div class="white-box user_list <% if list.private %>private_list<% end %>">
			
				<% if current_user?(list.user) %>
				  <%= link_to "&times;".html_safe, [current_user, list], class: "close", method: :delete,
				                                data: { confirm: "You sure?" },
				                                title: list.name %>
				<% end %>
			
			
				<div class="user_list_title">
					<h3><%= link_to list.name, user_list_path(@user, list) %></h3>
					<p class="muted" id="wishes_count">
						<% if list.private %><a href="#" class="muted tooltip-toggle" rel="tooltip" data-toggle="tooltip" data-title="This list is private"><i class="fa fa-lock"></i></a><% end %>
						<%= pluralize(list.wishes.count, "wish") %>
					</p>
				</div>

			<ul class="user_list_wishes <% if current_user?(list.user) %>dragndrop<% end %> unstyled hidden-phone" id="wishes_<%= list.id %>" data-update-url="<%= sort_wishes_url %>" data-list-id="<%= list.id %>">

				<!-- List wishes -->
				<% if list.wishes.any? %>
					<% list.wishes.includes(:item).rank(:row_order).each do |wish| %>
						<%= render partial: 'wishes/wish', locals: {wish: wish, size: "small"} %>
					<% end %>
				<% end %>
				<%= render partial: 'shared/list_wo_wish', locals: {list: list} %>
			</ul>
			<% if current_user?(list.user) %>
				<%= link_to "Add wish", new_item_path, {remote: true, 'data-toggle' => 'modal', 'data-target' => "#make_wish", id: "add_wish", class: "user_list_add_wish"} %>
			<% end %>
		</div>
	</div>
<% else %>
<!-- Aside sidebar lists -->
	<li class="aside_user_list_wish">
		<div class="block pull-left">
			<%= image_tag(list.wishes.last.item.image_url(:thumb).to_s, class: "img-rounded") if list.wishes.last %>
		</div>
	  <div class="block block-content">
	  	<span class="content">
	  		<span><%= link_to list.name, user_list_path(@user, list) %></span>
			  <span class="timestamp">
			    Updated <%= time_ago_in_words(list.updated_at) %> ago.			        
			  </span>
	  	</span>
	  </div>
	</li>
<% end %>

app/views/lists/_list.html.erb
<% if current_page?(user_path(@user)) && params[:view] != "organize" %> 
<% wishes = list.wishes.includes(:item).rank(:row_order).limit(4) %>
<!-- Profile lists -->
	<div class="span4">
		<div class="white-box item item-list">
			<div class="image-container">
				<a href="<%= user_list_path(@user,list) %>" class="item-link">
					<em class="mark visible-desktop">
						<p class="muted"><%= list.description %></p>
					</em>
					<% if wishes[0] %>
						<%= image_tag wishes[0].item.image_url(:medium).to_s %>
					<% else  %>
						<%= render partial: 'shared/list_wo_wish', locals: {list: list} %>
					<% end %>
					<div class="row-of-3">
						<% wishes.limit(3).offset(1).each do |wish| %>
							<div class="item-in-row">
								<%= image_tag wish.item.image_url(:thumb).to_s %>
							</div>
						<% end %>
					</div>
				</a>
			</div>
			<h3 class="ellipsis"><%= truncate(list.name, length: 53) %></h3>
			<% if list.private %><a href="#" class="muted tooltip-toggle" rel="tooltip" data-toggle="tooltip" data-title="This list is private"><i class="fa fa-lock"></i></a><% end %>
			<span class="muted"><%= pluralize(list.wishes.count, 'wish') %></span>
		</div>
	</div>

<% elsif current_page?(user_path(@user)) && params[:view] == "organize" %> 
	<div class="span6">
		<div class="white-box user_list <% if list.private %>private_list<% end %>">
			
				<% if current_user?(list.user) %>
				  <%= link_to "&times;".html_safe, [current_user, list], class: "close", method: :delete,
				                                data: { confirm: "You sure?" },
				                                title: list.name %>
				<% end %>
			
			
				<div class="user_list_title">
					<h3><%= link_to list.name, user_list_path(@user, list) %></h3>
					<p class="muted" id="wishes_count">
						<% if list.private %><a href="#" class="muted tooltip-toggle" rel="tooltip" data-toggle="tooltip" data-title="This list is private"><i class="fa fa-lock"></i></a><% end %>
						<%= pluralize(list.wishes.count, "wish") %>
					</p>
				</div>

			<ul class="user_list_wishes <% if current_user?(list.user) %>dragndrop<% end %> unstyled hidden-phone" id="wishes_<%= list.id %>" data-update-url="<%= sort_wishes_url %>" data-list-id="<%= list.id %>">

				<!-- List wishes -->
				<% if list.wishes.any? %>
					<% list.wishes.includes(:item).rank(:row_order).each do |wish| %>
						<%= render partial: 'wishes/wish', locals: {wish: wish, size: "small"} %>
					<% end %>
				<% end %>
				<%= render partial: 'shared/list_wo_wish', locals: {list: list} %>
			</ul>
			<% if current_user?(list.user) %>
				<%= link_to "Add wish", new_item_path, {remote: true, 'data-toggle' => 'modal', 'data-target' => "#make_wish", id: "add_wish", class: "user_list_add_wish"} %>
			<% end %>
		</div>
	</div>
<% else %>
<!-- Aside sidebar lists -->
	<li class="aside_user_list_wish">
		<div class="block pull-left">
			<%= image_tag(list.wishes.last.item.image_url(:thumb).to_s, class: "img-rounded") if list.wishes.last && list.wishes.last.item  %>
		</div>
	  <div class="block block-content">
	  	<span class="content">
	  		<span><%= link_to list.name, user_list_path(@user, list) %></span>
			  <span class="timestamp">
			    Updated <%= time_ago_in_words(list.updated_at) %> ago.			        
			  </span>
	  	</span>
	  </div>
	</li>
<% end %>

app/views/lists/index.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="span12 user_info">
    <%= render 'shared/user_info' %>
  </div>

  <div class="span12">
    <%= render 'shared/wish_list_sort' %>
    <div class="row">
      <% if @user.lists.any? %>
        <%= render @lists %> 
      <% else %>
        <!-- TODO: RENDER NO_LISTS -->
      <% end %>
      <% if current_user?(@user) %>
        <div class="span4">
          <div class="white-box" id="new_list_link">
            <%= link_to "New wish list", new_user_list_path, remote: true %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/lists/new.js.erb
$('#new_list_link').hide().after('<%= j render("shared/create_list") %>');
$('#appendedInputButton').focus();
// $('#create_list').focusout(function() {
// 	$('.create-list').remove();
// 	$('#new_list_link').show();
// });

app/views/lists/show.html.erb
<% provide(:title, @list.name) %>
<div class="row">
  <div class="span12 user_info">
    <div class="row">
      <div class="span9">
        <%= render partial: 'shared/user_info', locals: {:user => @user} %>
      </div>
      <%= render partial: 'users/follow_stats', locals: {:subject => @user} %>
    </div>
  </div>
</div>
<div class="row">
  <div class="span9">
      <div class="white-box user_list user_list_large">
        <% if current_user?(@list.user) %>
          <a href="#edit_list" role="button" data-toggle="modal" class="pull-right btn edit_list_btn"><i class="fa fa-pencil"></i></a>
        <% end %>
        <div class="user_list_title text-center">
          <h2><%= best_in_place_if current_user?(@list.user), [@user, @list], :name, nil: "Please name your list" %></h2>
          <% if @list.description %>
            <p><%= @list.description %></p>
          <% end %>
          <p class="muted list_meta">
            <% if @list.private? %><span><a href="#" class="muted tooltip-toggle" rel="tooltip" data-toggle="tooltip" data-title="This list is private"><i class="fa fa-lock"></i></a></span><% end %>
            <span><%= pluralize(@list.wishes.count, "wish") %></span>
            <span><i class="fa fa-clock-o"></i> Updated <%= time_ago_in_words(@list.updated_at) %> ago</span>
          </p>
        </div>
        <ul class="wishes <% if current_user?(@list.user) %>dragndrop<% end %> unstyled" id="list_<%= @list.id %>" data-update-url="<%= sort_wishes_url %>" data-list-id="<%= @list.id %>">
          <% if @list.items.any? %>
            <%= render @wishes, size: "large" %>
          <% else %>
            <%= render partial: 'shared/list_wo_wish', locals: {list: @list} %>
          <% end %>
          <% if current_user?(@list.user) %>
            <%= link_to "Add wish", new_item_path, {remote: true, 'data-toggle' => 'modal', 'data-target' => "#make_wish", id: "add_wish", class: "user_list_add_wish"} %>
          <% end %>
        </ul>
      </div>
  </div>

  <aside class="pull-right span3">
    <%= render 'shared/aside_share' if current_user?(@list.user) %>
    <%= render 'shared/aside_lists' %>
  </aside>

</div>

<!-- Modal -->
<div id="edit_list" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="edit_list" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="share_list">Edit list</h3>
  </div>
  <%= form_for [@user, @list], html: {class: "form-horizontal"} do |f| %>
    <div class="modal-body">    

      <div class="control-group">
        <%= f.label :name, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :name, placeholder: "Eg. My Wish List" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :description, class: "control-label" %>
        <div class="controls">
          <%= f.text_area :description, placeholder: "What's your list for?", rows: 4 %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :private, "Private?", class: "control-label" %>
          <div class="controls">
            <label class="checkbox">
              <span class="icons">
                <span class="first-icon fui-checkbox-unchecked"></span>
                <span class="second-icon fui-checkbox-checked"></span>
              </span>
              <%= f.check_box :private %>
            </label>
            <p class="muted">Private lists are only visible to the people you invited. Invite people in the sidebar to the right.</p>
          </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>