config/routes.rb
Wishlist::Application.routes.draw do

  resources :likes

  resources :admissions

  resources :activities

  match '/header_index', to: 'activities#header_index'

  use_link_thumbnailer

  namespace :plugin do
    match '/', to: 'lists#index'
    resources :lists
    resources :sessions
    resources :users

    match '/script', to: 'script#get'
    match '/widget', to: 'widget#index'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy'
    match '/signup', to: 'users#new'
  end

  match '/bookmarklet', to: 'items#bookmarklet'

  namespace :admin do
    resources :users, :items, :wishes, :comments
    match '/lptester', to: 'items#lptester'
  end

  resources :items, only: [:show, :new, :create, :update, :destroy, :inspiration] do
    resources :comments, :defaults => { :commentable => 'item' }
  end
  resources :wishes do
    collection { post :sort }
    resources :comments, :defaults => { :commentable => 'wish' }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reservations
  resources :vendors, only: [:index, :new, :create]
  resources :vendors, path: "v" , except: [:index, :new, :create]
  resources :password_resets

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match 'auth/:provider/callback', to: 'sessions#create_with_oauth'
  match 'auth/failure', to: redirect('/')

  root to: 'static_pages#home'
  get "sitemap.xml", to: "static_pages#sitemap", defaults: { format: "xml" }

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/privacy', to: 'static_pages#privacy'
  match '/terms',   to: 'static_pages#terms'
  match '/linkpreview', to: 'items#linkpreview'
  match '/inspiration', to: 'items#inspiration'
  match '/search',  to: 'static_pages#search'
  match 'contact_support', to: 'mailing#contact_support'

  match '/item_suggestion', to:'items#item_suggestion'
  match '/user_suggestion', to:'users#invite_suggestion'
  match '/vendor_suggestion', to:'vendors#invite_suggestion'

  match 'v/:id/edit_admins', to: 'vendors#edit_admins', as: 'edit_admins'

  match '/:id/update_password', to: 'users#update_password', as: 'update_password'
  match '/:id/update_notifications', to: 'users#update_notifications', as: 'update_notifications'

  resources :users, only: [:index, :new, :create]
  resources :users, path: "" , except: [:index, :new, :create] do
    resources :comments, :defaults => { :commentable => 'user' }
    resources :lists do
      post :share
    end
    member do
      get :following, :defaults => { :followed => 'user' }
      get :followers, :defaults => { :followed => 'user' }
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  helper_method :sort_general, :sort_gender
  include Analyzable

  def home
    redirect_to inspiration_path if signed_in?
    @items = Item.sort(sort_general, sort_gender, current_user).page(params[:page]).per_page(9)
    if cookies[:mp_distinct_id] && mp_id
      tracker.track(mp_id, 'Visits landing page')
    end
    # if params[:sort] == "recent"
    #   @items = Item.recent.page(params[:page]).per_page(9)
    # elsif params[:sort] == "popular"
    #   @items = Item.popular.page(params[:page]).per_page(9)
    # else
    #   @items = Item.recent.page(params[:page]).per_page(9)
    # end

  end

  def help
  end

  def about
    if signed_in?
      tracker.track(current_user.id, 'Visits about')
    else
      tracker.track(cookies[:mp_distinct_id].split("%22")[3], 'Visits about') if cookies[:mp_distinct_id]
    end
  end

  def contact
    @message = Message.new
  end

  def privacy
  end

  def terms
  end

  def search
    if params[:search]
      @users = User.search(params[:search]).most_followers.limit(10)
      @vendors = Vendor.search(params[:search]).most_followers.limit(10)
      @items = Item.search(params[:search]).popular.paginate(page: params[:page], per_page: 10)
    else
      @users = User.most_followers.limit(10)
      @vendors = Vendor.most_followers.limit(10)
      @items = Item.popular.paginate(page: params[:page], per_page: 10)
    end
  end

  def sitemap
    @static_paths = [inspiration_url, about_url, contact_url]
    @items = Item.popular
    @users = User.top_wishers
    respond_to do |format|
      format.xml
    end
  end

private
  def sort_general
    %w[recent popular following].include?(params[:sort]) ? params[:sort] : "popular"
  end

  def sort_gender
    %w[Male Female].include?(params[:gender]) ? params[:gender].titleize : "all"
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_searchresult.html.erb
<% if searchresult.class.name == "User" %>
	<%= render 'users/user', user: searchresult %>
<% else %>
	 <%= render 'vendors/user', user: searchresult %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="row">
	<div class="spacer"></div>
	<div class="span12 text-center">
		<h1>Collect, organize and share your wish list.</h1>
		<h2>Welcome to the universe of Halusta</h2>
	</div>
	<div class="spacer"></div>
</div>
<div class="row">
  <div class="span10 offset1">
		<p>Make a wish when you see a shooting star, blow out the candles on your birthday cake, toss a coin into a wishing well – or make a wish on Halusta and share your wishes with friends, family and the whole universe of Halusta for your wishes to come true!</p>

		<p>Halusta makes you able to collect, organize and share your wish lists. Easily keep track of products you wish for by adding wishes to your lists using the “Halusta button", when you see something you like anywhere on the web, and simply share your wish lists with friends and family for your birthday, anniversary or Christmas.</p>

		<p>At the same time, Halusta is also a social universe, where you go to get inspired! Browse the “Find inspiration” tabs to find inspiring products for your wardrobe, house, gadget collection, bookshelf or backpack or follow your friends, favorite bloggers, preferred stores and other exiting Halusta wishers.</p>

		<p>Halusta was founded in Copenhagen in 2013 and is now changing the way people share wishes</p>
  </div>
</div>
<div class="row">
	<div class="spacer"></div>
	<div class="span8 offset2 about-boxes">
  	<h2 class="text-center">How it works</h2>
		<span class="text-left">
			<div class="about-imgs pull-left">
				<%= image_tag 'about-collect.gif', class: "animated" %>
				<%= image_tag 'about-collect.png', class: "non-animated" %>
			</div>
			<h2>Collect</h2>
			<p>Easily add products to your wishl ist from around the web with the Halusta button.</p>
	 	</span>
	 	<div class="spacer"></div>
	 	<span class="text-right">
			<div class="about-imgs pull-right">
				<%= image_tag 'about-organize.gif', class: "animated" %>
				<%= image_tag 'about-organize.png', class: "non-animated" %>
			</div>
			<h2>Organize</h2>
			<p>Halusta allows you to easily arrange and sort wishes across all your wishlists.</p>
	 	</span>
	 	<div class="spacer"></div>
		<span class="text-left">
			<div class="about-imgs pull-left">
				<%= image_tag 'about-share.gif', class: "animated" %>
				<%= image_tag 'about-share.png', class: "non-animated" %>
			</div>
			<h2>Share</h2>
			<p>With one click you can e-mail your wishlist to friends and family or export it to PDF.</p>
	 	</span>
	</div>
</div>
<div class="row">
	<div class="spacer"></div>
	<div class="spacer"></div>
	<div class="span12">
		<%= render 'shared/wide_facebook' %>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="row">
	<div class="span12">
		<h1>Contact</h1>
	</div>
</div>
<div class="row">
  <div class="span9">
  	<div class="spacer"></div>
  	<address>
		  <strong>Halusta IVS</strong><br>
		  <abbr title="Company Number">CVR:</abbr> 35843019
		</address>
		
		<%= form_for @message, url: contact_support_path do |f| %>

			<%= f.label :subject %>
			<%= f.text_field :subject %>

			<%= f.label :casetype, "Type of case" %>
			<%= f.select :casetype, [['Please select a case type', 'no-select'], ['Possible problem', 'problem'], ['Feedback', 'feedback'], ['Business Inquiries', 'business'], ['Advertising', 'advertising'], ['Other', 'other']] %>

			<%= f.label :name %>
			<%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email, placeholder: "john@doe.com" %>
    
      <%= f.label :body, "Message" %>
      <%= f.text_area :body, rows: 6 %>

		  <%= f.submit "Send", class: "btn btn-primary" %>

		<% end %>

  </div>
  <aside class="pull-right span3">
    <%= render 'shared/aside_hq' %>
    <%= render 'shared/aside_facebook' %>
  </aside>

</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
Coming soon...
</p>

app/views/static_pages/home.html.erb
<div class="row home_about center">
	<div class="span12">
		<h1>How it works</h1>
	</div>
	<div class="span4">
		<div class="about-imgs">
			<%= image_tag 'about-collect.gif', class: "animated" %>
			<%= image_tag 'about-collect.png', class: "non-animated" %>
		</div>
		<h2>Collect</h2>
		<p>Easily add products to your wishlist from around the web with the Wishlistt button.</p>
 	</div>
 	<div class="span4">
		<div class="about-imgs">
			<%= image_tag 'about-organize.gif', class: "animated" %>
			<%= image_tag 'about-organize.png', class: "non-animated" %>
		</div>
		<h2>Organize</h2>
		<p>Wishlistt allows you to easily arrange and sort wishes across all your wishlists.</p>
 	</div>
	<div class="span4">
		<div class="about-imgs">
			<%= image_tag 'about-share.gif', class: "animated" %>
			<%= image_tag 'about-share.png', class: "non-animated" %>
		</div>
		<h2>Share</h2>
		<p>With one click you can e-mail your wishlist to friends and family or export it to PDF.</p>
 	</div>
</div>
<hr>
<div class="items_home">
	<div class="center">
		<h1>Popular wishes</h1>
	</div>
	<div class="spacer"></div>
	<div class="row">
	  <%= render @items.limit(6) %>
	</div>
	<div class="center">
		<%= link_to "Find more inspiration", inspiration_path, class: "btn", id: "home_inspiration" %>
	</div>
</div>
<hr>
<div class="signup_home center">
	<h3>Start collecting your wishes!</h3>
	<div class="spacer"></div>
	<a href="#signUp" id="bottom_home_signup" role="button" class="btn btn-large btn-primary" data-toggle="modal">Sign up for free</a>
</div>
<div class="center">
	<%= render 'shared/wide_facebook' %>
</div>

app/views/static_pages/home.js.erb
$('.items_home').append('<%= j render(@items) %>');
<% if @items.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@items) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/static_pages/privacy.html.erb
<% provide(:title, 'Privacy Policy') %>

<div class="row">
	<div class="span12">
		<h1>Privacy Policy</h1>
	</div>
</div>
<div class="row">
	<div class="span9">
		<p class="lead">
			Your privacy is critically important to us. At Halusta we have a few fundamental principles:
		</p>
		<ul>
			<li>
				We don&#8217;t ask you for personal information unless we truly need it. (We can&#8217;t stand services that ask you for things like your gender or income level for no apparent reason.)
			</li>
			<li>
				We don&#8217;t share your personal information with anyone except to comply with the law, develop our products, or protect our rights.
			</li>
			<li>
				We don&#8217;t store personal information on our servers unless required for the on-going operation of one of our services.
			</li>
		</ul>
		<p>
			Below is our privacy policy which incorporates these goals:
		</p>
		<p>
			If you have questions about deleting or correcting your personal data please contact our <a href="http://www.Halusta.com/contact">support team</a>.
		</p>
		<p>
			Halusta (“<strong>Halusta</strong>”) operates <a href="http://www.Halusta.com/">Halusta.com</a>. It is Halusta’s policy to respect your privacy regarding any information we may collect while operating our websites.
		</p>
		
		<h3>Website Visitors</h3>
		<p>
			Like most website operators, Halusta collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Halusta&#8217;s purpose in collecting non-personally identifying information is to better understand how Halusta&#8217;s visitors use its website. From time to time, Halusta may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.
		</p>
		<p>
			Halusta also collects potentially personally-identifying information like Internet Protocol (IP) addresses. Halusta does not use such information to identify its visitors, however, and does not disclose such information, other than under the same circumstances that it uses and discloses personally-identifying information, as described below.
		</p>

		<h3>Gathering of Personally-Identifying Information</h3>
		<p>
			Certain visitors to Halusta’s websites choose to interact with Halusta in ways that require Halusta to gather personally-identifying information. The amount and type of information that Halusta gathers depends on the nature of the interaction. For example, we ask visitors who sign up for an account at <a href="http://www.Halusta.com/">Halusta.com</a> to provide a username and email address. Those who engage in transactions with Halusta are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case, Halusta collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor’s interaction with Halusta. Halusta does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.
		</p>

		<h3>Aggregated Statistics</h3>
		<p>
			Halusta may collect statistics about the behavior of visitors to its websites. Halusta may display this information publicly or provide it to others. However, Halusta does not disclose personally-identifying information other than as described below.
		</p>

		<h3>Protection of Certain Personally-Identifying Information</h3>
		<p>
			Halusta discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on Halustas behalf or to provide services available at Halustas websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using Halustas websites, you consent to the transfer of such information to them. Halusta will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, Halusta discloses potentially personally-identifying and personally-identifying information only when required to do so by law, or when Halusta believes in good faith that disclosure is reasonably necessary to protect the property or rights of Halusta, third parties or the public at large. If you are a registered user of an Halusta website and have supplied your email address, Halusta may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with whats going on with Halusta and our products. We primarily use our various product blogs to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. Halusta takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.
		</p>

		<h3>Cookies</h3>
		<p>
			A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. Halusta uses cookies to help Halusta identify and track visitors, their usage of Halusta website, and their website access preferences. Halusta visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using Halusta’s websites, with the drawback that certain features of Halusta’s websites may not function properly without the aid of cookies.
		</p>

		<h3>Business Transfers</h3>
		<p>
			If Halusta, or substantially all of its assets, were acquired, or in the unlikely event that Halusta goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of Halusta may continue to use your personal information as set forth in this policy.
		</p>

		<h3>Ads</h3>
		<p>
			Ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by Halusta and does not cover the use of cookies by any advertisers.
		</p>

		<h3>Privacy Policy Changes</h3>
		<p>
			Although most changes are likely to be minor, Halusta may change its Privacy Policy from time to time, and in Halusta’s sole discretion. Halusta encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.
		</p>

		<p class="muted">This Privacy Policy was crafted from <a href="http://automattic.com/privacy/">Wordpress.com's version</a>, which is available under a Creative Commons Sharealike license.</p>
	</div>
</div>

app/views/static_pages/search.html.erb
<% provide(:title, 'Search') %>
<div class="row">
	<div class="span12">
		<h1>Search for friends, products or vendors</h1>
		<p>Browse, or search below</p>
		<div>
			<%= form_tag(search_path, :method => "get", id: "search-form", class: "form-search form-inline") do %>
				<%= text_field_tag :search, params[:search], class: "span6", placeholder: "Search for friends, vendors or products" %>
				<%= submit_tag "Search", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

<div class="row">
	<div class="span8">
		<div class="spacer"></div>
		<div class="row inspiration">
		  <%= render @items %>
		  <% if @items.empty? %>
		  	<h2 class="center muted">No products found</h2>
		  <% end %>
		</div>

		<div id="inspiration-pagination">
			<%= will_paginate @items %>
		</div>
	</div>
	
	<aside class="pull-right span4">
		<% if current_user.admin? %>
			<div class="admin">
			  <h3>Admin-info</h3>
			  <span>
			  	<p><%= Item.all.count %> items in total</p>
			  </span>
			  <span>
			  	<p><%= User.all.count %> users in total</p>
			  </span>
			  <span>
			  	<p><%= Vendor.all.count %> vendors in total</p>
			  </span>
			</div>
		<% end %>
		<%= render 'shared/aside_users' %>
		<%= render 'shared/aside_vendors' %>
	</aside>
</div>

app/views/static_pages/search.js.erb
$('.inspiration').append('<%= j render(@items) %>');
<% if @items.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@items) %>');
<% else %>
  $('.pagination').remove();
<% end %>