config/routes.rb
Wishlist::Application.routes.draw do

  resources :likes

  resources :admissions

  resources :activities

  match '/header_index', to: 'activities#header_index'

  use_link_thumbnailer

  namespace :plugin do
    match '/', to: 'lists#index'
    resources :lists
    resources :sessions
    resources :users

    match '/script', to: 'script#get'
    match '/widget', to: 'widget#index'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy'
    match '/signup', to: 'users#new'
  end

  match '/bookmarklet', to: 'items#bookmarklet'

  namespace :admin do
    resources :users, :items, :wishes, :comments
    match '/lptester', to: 'items#lptester'
  end

  resources :items, only: [:show, :new, :create, :update, :destroy, :inspiration] do
    resources :comments, :defaults => { :commentable => 'item' }
  end
  resources :wishes do
    collection { post :sort }
    resources :comments, :defaults => { :commentable => 'wish' }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reservations
  resources :vendors, only: [:index, :new, :create]
  resources :vendors, path: "v" , except: [:index, :new, :create]
  resources :password_resets

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match 'auth/:provider/callback', to: 'sessions#create_with_oauth'
  match 'auth/failure', to: redirect('/')

  root to: 'static_pages#home'
  get "sitemap.xml", to: "static_pages#sitemap", defaults: { format: "xml" }

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/privacy', to: 'static_pages#privacy'
  match '/terms',   to: 'static_pages#terms'
  match '/linkpreview', to: 'items#linkpreview'
  match '/inspiration', to: 'items#inspiration'
  match '/search',  to: 'static_pages#search'
  match 'contact_support', to: 'mailing#contact_support'

  match '/item_suggestion', to:'items#item_suggestion'
  match '/user_suggestion', to:'users#invite_suggestion'
  match '/vendor_suggestion', to:'vendors#invite_suggestion'

  match 'v/:id/edit_admins', to: 'vendors#edit_admins', as: 'edit_admins'

  match '/:id/update_password', to: 'users#update_password', as: 'update_password'
  match '/:id/update_notifications', to: 'users#update_notifications', as: 'update_notifications'

  resources :users, only: [:index, :new, :create]
  resources :users, path: "" , except: [:index, :new, :create] do
    resources :comments, :defaults => { :commentable => 'user' }
    resources :lists do
      post :share
    end
    member do
      get :following, :defaults => { :followed => 'user' }
      get :followers, :defaults => { :followed => 'user' }
    end
  end

end

app/views/shared/_add_wish.html.erb
<div id="make_wish" class="modal hide fade" tabindex="1" role="dialog" aria-labelledby="make_wish" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="make_wish">Make a wish</h3>
  </div>

  <div id="modal-default">
      <%= render 'shared/quick_wish' %>
  </div>

  <div id="modal-secondary"  style="display:none;">
    <div id="modal-secondary-body" class="modal-body">
      <div class="spacer"></div>
      <div class="spacer"></div>

      <div class="text-center">
        <p>Drag this button to your bookmarks bar and press it whenever you find something on a webshop that you like.</p>
        <a href="javascript:(function()%7Bvar%20script=document.createElement('SCRIPT');script.src='<%= request.protocol %><%= request.host_with_port %>/assets/bookmarklet/wishlistt_tagger.js?r='+Math.random()*99999999;document.body.appendChild(script);%7D)()" class="btn btn-success">Save to Halusta</a>
      </div>

      <div class="spacer"></div>
      <div class="spacer"></div>
    </div>
    <div id="modal-default-footer" class="modal-footer">
      <a class="muted pull-left" href="#" id="btn-to-modal-default">Back</a>
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <!-- <a href="#" id="urlb" role="button" class="btn btn-primary">Add wish</a> -->
    </div>
  </div>
</div>

app/views/shared/_aside_facebook.html.erb
<div class="facebook">
  <h3>Follow us on Facebook</h3>
  <span>
  	<iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fhalustacom&amp;width=232&amp;height=400&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false&amp;appId=436111449777435" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:232px; height:400px;" allowTransparency="true"></iframe>
  </span>
</div>

app/views/shared/_aside_follow_fb_friends.html.erb
<% unless users.all?(&:blank?) %>
	<div class="aside_users">
	  <h3>Friends already on Halusta</h3>
	  <ul class="unstyled">
	    <% users.each do |user| %>
	    	<li class="aside_search_result">
	      		<%= link_to(user) do %>
	      			<div class="block pull-left">
	      				<%= image_tag avatar(user, :small), alt: user.name, class: "gravatar gravatar-small img-rounded" %>
							</div>
							<div class="block block-content ellipsis">
	      				<%= truncate(user.name) %> <%= render partial: 'users/follow_form', locals: {subject: user, size: "small"} %>
	      			</div>
	      		<% end %>
	    	</li>
	    <% end %>
	  </ul>	
	</div>
<% end %>

app/views/shared/_aside_hq.html.erb
<div class="hq">
  <h3>Halusta HQ</h3>
  <span>
  	<img src="http://maps.googleapis.com/maps/api/staticmap?center=Copenhagen,Denmark&zoom=11&size=220x220&maptype=roadmap
&markers=55.69436,12.54365&sensor=false" alt="">
  </span>
</div>

app/views/shared/_aside_share.html.erb
<div class="share">
  <h3>Share</h3>
  <ul class="muted fa-ul">
  	<% unless @list.private? %>
			<li>
				<a href="#">
					<i class="fa-li fa fa-link"></i> <input type="url" readonly onClick="this.select();" value="halusta.com<%= request.fullpath %>">
				</a>
			</li>
		<% end %>
		<li>
			<a href="#share_list" role="button" data-toggle="modal">
				<% if @list.private? %>
					<i class="fa-li fa fa-envelope"></i> Invite people
				<% else %>
					<i class="fa-li fa fa-envelope"></i> Send with e-mail
				<% end %>
			</a>
		</li>
		<!-- <li>
			<a href="#">
				<i class="icon-share"></i> Export to PDF
			</a>
		</li> -->
  </ul>
</div>

<!-- Modal -->
<div id="share_list" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="share_list" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="share_list">Share list</h3>
  </div>

  <% if @list.private? %>
		<%= form_for @list.admissions.new, remote: true do |f| %>
			<div class="modal-body">
				<p>You set this list to 'private'. Nobody except the people you invited to the list is able to see it. Invite people to the list below.</p>
      	<%= text_field_tag :invite_to_secret, params[:search], :data => {:provide => "typeahead"}, autocomplete: :off, placeholder: "Type a name or email." %>
      	<%= f.hidden_field :accessible_id %>
      	<%= f.hidden_field :accessible_type %>
      	<%= f.hidden_field :user_id %>
      	<%= f.submit "Add", style: "display:none;" %>
      	<ul class="unstyled" id="admissions">
      		<h5>Who can see your list?</h5>
      		<%= render 'admissions/admission_user', user: @list.user, admission: nil %>
      		<% @list.admissions.each do |admission| %>
      			<%if admission.user %>
			    		<%= render 'admissions/admission_user', user: admission.user, admission: admission %>
			    	<% end %>
			    <% end %>
      	</ul>
      </div>
      <div class="modal-footer">
		    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		  </div>
    <% end %>
	<% else %>
	  <%= form_for @message, :url => user_list_share_path(@user, @list) do |f| %>
		  <div class="modal-body">    

	      <%= f.label :email %>
	      <%= f.text_field :email, placeholder: "john@doe.com" %>
	    
	      <%= f.label :body, "Message" %>
	      <%= f.text_area :body, value: "Hi, this is my wish list :)", placeholder: "Message" %>

	  	</div>
		  <div class="modal-footer">
		    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
				<%= f.submit "Send", class: "btn btn-primary" %>
		  </div>
		<% end %>
	<% end %>
</div>

app/views/shared/_aside_vendors.html.erb
<div class="aside_vendors">
  <h3>Vendors to follow</h3>
  	<% if @vendors.first.present? %>
	    <ul class="unstyled">
	      <% @vendors.each do |vendor| %>
	      	<li class="aside_search_result">
		      		<%= link_to(vendor) do %>
		      			<div class="block pull-left">
		      				<%= image_tag "default_images/vendor.png", alt: vendor.name, class: "gravatar gravatar-small img-rounded" %>
								</div>
								<div class="block block-content">
		      				<%= vendor.name %>
		      			</div>
		      		<% end %>
	      	</li>
	      <% end %>
	      <li class="text-right"><%= link_to "Full result", vendors_path(search: params[:search]) %></li>
	    </ul>
	  <% else %>
	  	<p class="muted center">No vendors found</p>
	  <% end %>
  
</div>

app/views/shared/_create_list.html.erb
<div class="white-box create-list" id="create_list">
	<%= form_for([current_user, @list]) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <div class="input-append">
	    <%= f.text_field :name, placeholder: "Create new list...", id:"appendedInputButton" %>
	    <%= f.submit "Add", class: "btn" %>
	  </div>
	<% end %>
</div>

app/views/shared/_list_add_wish.html.erb
<div class="center list_add_wish">
	<%= link_to "Add wish", new_item_path, {remote: true, 'data-toggle' => 'modal', 'data-target' => "#make_wish", id: "add_wish", class: "btn btn-primary"} if current_user?(@user) %>
</div>

app/views/shared/_list_wo_wish.html.erb
<li class="no-wish center" <% if list.wishes.any? %>style="display:none"<% end %>>
	<% if current_user?(@user) %>
		<%= image_tag('default_images/thumb_gift.png', size: "60x60") %>
		<h3 class="muted">A list without a wish is no wish list!</h3>
		<p>Begin collecting your wishes by clicking the green 'make a wish' button in the navbar. It's super easy!</p>
	<% else %>
		<%= image_tag('default_images/thumb_gift.png', size: "60x60") %>
		<h3 class="muted">This list has no wishes yet</h3>
	<% end %>
</li>

app/views/shared/_make_a_wish.html.erb
<div id="make_wish" class="modal hide fade" tabindex="1" role="dialog" aria-labelledby="make_wish" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="make_wish">Make a wish</h3>
  </div>
  <div id="linkpreview">
    <%= form_tag '/linkpreview', id: "linkpreview_form", remote: true do %>
      <div id="modal-default-body" class="modal-body">
        <div class="center hidden-phone">
          <div class="spacer"></div>
          <div class="spacer"></div>
          <p>Drag this button to your bookmark bar, and easily add items to your wish list.</p><a href="javascript:(function()%7Bvar%20script=document.createElement('SCRIPT');script.src='<%= request.protocol %><%= request.host_with_port %>/assets/bookmarklet/wishlistt_tagger.js?r='+Math.random()*99999999;document.body.appendChild(script);%7D)()" class="btn btn-success">Wishlistt it</a>
          <div class="spacer"></div>
          <hr>
        </div>
        
          <!-- <label for="url">or, paste the URL for the product you wish</label>
          <input id="url" type="text" placeholder="http://"> -->
          <%= label_tag :url, "or, paste the URL for the product you wish" %>
          <%= text_field_tag :url %>

      </div>
      <div id="modal-default-footer" class="modal-footer">
        <a href="#" id="manual_wish" class="muted pull-left">Add a wish manually</a>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <!-- <a href="#" id="urlb" role="button" class="btn btn-primary">Add wish</a> -->
        
        <%= submit_tag "Add wish", class: "btn btn-primary", id: "urlb" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_searchresult.html.erb
<% if searchresult.class.name == "User" %>
	<%= render 'users/user', user: searchresult %>
<% else %>
	 <%= render 'vendors/vendor', user: searchresult %>
<% end %>

app/views/shared/_user_info.html.erb
<% user ||= @user %>

  <a href="<%= user_path(user) %>">
    <%= image_tag avatar(user, :large), alt: user.name, class: "gravatar gravatar-large img-rounded" %>
  </a>

  <h1><%= link_to user.name, user, class: "no-color ellipsis" %></h1><%= render partial: 'users/follow_form', locals: {:subject => user} if signed_in? %>
  <span class="user-socials muted">
    <% if user.location? %>
      <span><i class="fa fa-map-marker"></i> <%= user.location %> </span>
    <% end %>
    <% if user.website? %> 
      <span>
        <%= link_to user.website, target: "_blank" do %>
        <i class="fa fa-globe"></i> <%= user.website.gsub("http://", '').gsub("https://", '').gsub("www.", '') %>
        <% end %>
      </span>
    <% end %>
    <% if user.twitter? %> 
      <span>
        <%= link_to "http://www.twitter.com/" + user.twitter, target: "_blank" do %>
          <i class="fa fa-twitter"></i>
        <% end %>
      </span>
    <% end %>
    <% if user.instagram? %> 
      <span>
        <%= link_to "http://www.instagram.com/" + user.instagram, target: "_blank" do %>
          <i class="fa fa-instagram"></i>
        <% end %>
      </span>
    <% end %>
    <% if user.pinterest? %> 
      <span>
        <%= link_to "http://www.pinterest.com/" + user.pinterest, target: "_blank" do %>
          <i class="fa fa-pinterest"></i>
        <% end %>
      </span>
    <% end %>
    <% if user.facebook? %> 
      <span>
        <%= link_to "http://www.facebook.com/" + user.facebook, target: "_blank" do %>
          <i class="fa fa-facebook"></i>
        <% end %>
      </span>
    <% end %>
  </span>
  <span class="user-bio">
    <%= user.bio %>
  </span>

<!-- <a href="#" class="btn">Follow</a> -->

app/views/shared/_vendor_info.html.erb
<% vendor ||= @vendor %>

  <a href="<%= vendor_path(vendor) %>">
    <%= image_tag avatar(vendor, :large), alt: vendor.name, class: "gravatar gravatar-large img-rounded" %>
  </a>

  <h1><%= link_to vendor.name, vendor, class: "no-color" %></h1>
  <% if current_user && vendor.allowed_access?(current_user) %>
  	<%= link_to "Edit", edit_vendor_path(vendor), class: "btn btn-default btn-edit-vendor" %>
  <% end %>
  <%= render partial: 'users/follow_form', locals: {:subject => vendor} if signed_in? %>
  
  <span class="user-socials muted">  
     <span><i class="fa fa-globe"></i> <%= link_to vendor.url, vendor.url, class: "muted", target: "_blank" %> </span>
    <% if vendor.twitter? %> 
      <span>
        <%= link_to "http://www.twitter.com/" + vendor.twitter, target: "_blank" do %>
          <i class="fa fa-twitter"></i>
        <% end %>
      </span>
    <% end %>
    <% if vendor.instagram? %> 
      <span>
        <%= link_to "http://www.instagram.com/" + vendor.instagram, target: "_blank" do %>
          <i class="fa fa-instagram"></i>
        <% end %>
      </span>
    <% end %>
    <% if vendor.pinterest? %> 
      <span>
        <%= link_to "http://www.pinterest.com/" + vendor.pinterest, target: "_blank" do %>
          <i class="fa fa-pinterest"></i>
        <% end %>
      </span>
    <% end %>
    <% if vendor.facebook? %> 
      <span>
        <%= link_to "http://www.facebook.com/" + vendor.facebook, target: "_blank" do %>
          <i class="fa fa-facebook"></i>
        <% end %>
      </span>
    <% end %>
  </span>
  <span class="user-bio">
    <%= vendor.bio %>
  </span>

<!-- <a href="#" class="btn">Follow</a> -->

app/views/shared/_wish_list_sort.html.erb
<span>
  <ul class="inline sortable">
    <li><%= nav_link "All wishes", user_path(@user) %></li>
    <li><%= nav_link "Wish Lists", user_lists_path(@user) %></li>
  </ul>
</span>