config/routes.rb
Wishlist::Application.routes.draw do

  resources :likes

  resources :admissions

  resources :activities

  match '/header_index', to: 'activities#header_index'

  use_link_thumbnailer

  namespace :plugin do
    match '/', to: 'lists#index'
    resources :lists
    resources :sessions
    resources :users

    match '/script', to: 'script#get'
    match '/widget', to: 'widget#index'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy'
    match '/signup', to: 'users#new'
  end

  match '/bookmarklet', to: 'items#bookmarklet'

  namespace :admin do
    resources :users, :items, :wishes, :comments
    match '/lptester', to: 'items#lptester'
  end

  resources :items, only: [:show, :new, :create, :update, :destroy, :inspiration] do
    resources :comments, :defaults => { :commentable => 'item' }
  end
  resources :wishes do
    collection { post :sort }
    resources :comments, :defaults => { :commentable => 'wish' }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reservations
  resources :vendors, only: [:index, :new, :create]
  resources :vendors, path: "v" , except: [:index, :new, :create]
  resources :password_resets

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match 'auth/:provider/callback', to: 'sessions#create_with_oauth'
  match 'auth/failure', to: redirect('/')

  root to: 'static_pages#home'
  get "sitemap.xml", to: "static_pages#sitemap", defaults: { format: "xml" }

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/privacy', to: 'static_pages#privacy'
  match '/terms',   to: 'static_pages#terms'
  match '/linkpreview', to: 'items#linkpreview'
  match '/inspiration', to: 'items#inspiration'
  match '/search',  to: 'static_pages#search'
  match 'contact_support', to: 'mailing#contact_support'

  match '/item_suggestion', to:'items#item_suggestion'
  match '/user_suggestion', to:'users#invite_suggestion'
  match '/vendor_suggestion', to:'vendors#invite_suggestion'

  match 'v/:id/edit_admins', to: 'vendors#edit_admins', as: 'edit_admins'

  match '/:id/update_password', to: 'users#update_password', as: 'update_password'
  match '/:id/update_notifications', to: 'users#update_notifications', as: 'update_notifications'

  resources :users, only: [:index, :new, :create]
  resources :users, path: "" , except: [:index, :new, :create] do
    resources :comments, :defaults => { :commentable => 'user' }
    resources :lists do
      post :share
    end
    member do
      get :following, :defaults => { :followed => 'user' }
      get :followers, :defaults => { :followed => 'user' }
    end
  end

end

app/models/vendor.rb
# == Schema Information
#
# Table name: vendors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  url        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string(255)
#  bio        :text
#  twitter    :string(255)
#  instagram  :string(255)
#  pinterest  :string(255)
#  facebook   :string(255)
#  avatar     :string(255)
#

class Vendor < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  mount_uploader :avatar, AvatarUploader

  attr_accessible :name, :url, :avatar, :remove_avatar, :bio, :twitter, :instagram, :pinterest, :facebook

  has_many :items, dependent: :destroy
  has_many :wishes, through: :items

  has_many :relationships, as: :followed
  has_many :followers, through: :relationships, source: :follower

  has_many :admissions, as: :accessible

  validates :slug, uniqueness: true, presence: true
  validates :name, presence: true

  validates :bio, length: { maximum: 160 }
  validates :twitter, length: { maximum: 15 }
  validates :instagram, length: { maximum: 30 }
  validates :pinterest, length: { maximum: 15 }

	before_validation :create_unique_slug

	def to_param
		slug
	end

	def create_unique_slug
		if self.new_record? || self.slug.blank?
      if Vendor.where(:slug => name.parameterize).count > 0
        n = 1
        while Vendor.where(:slug => "#{self.name.parameterize}-#{n}").count > 0
          n += 1
        end
        self.slug = "#{self.name.parameterize}-#{n}"
      else
        self.slug = self.name.parameterize
      end
    end
	end

  def self.custom_find_or_create(link)
  	name = ApplicationController.helpers.get_host_without_www(link)
  	vendor = Vendor.create_with(url: ApplicationController.helpers.get_host_with_www(link)).find_or_create_by_name(name)
  	return vendor.id
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("upper(vendors.name) like upper(?)", "%#{query}%") 
  end

  def base_uri
    vendor_path(self)
  end

  def self.most_followers
    joins("left join relationships on relationships.followed_id = vendors.id AND relationships.followed_type = 'Vendor'")
    .select('vendors.*, count(relationships.followed_id) as relationships_count')
    .group('vendors.id')
    .order('relationships_count desc, vendors.created_at desc')
  end

  def allow_access(user)
    self.admissions.create!(user_id: user.id)
  end

  def allowed_access?(user = nil)
    user = user.nil? ? current_user : user
    self.admissions.find_by_user_id(user).present?
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
	helper_method :sort_general, :sort_gender
	before_filter :find_vendor, only: [:show, :edit, :update, :destroy, :edit_admins]
	before_filter :correct_user, only: [:edit, :update]

	def new
		Vendor.new
	end

	def create
		@vendor = Vendor.create!(params[:vendor])
	end

	def show
		@items = Item.sort(sort_general, sort_gender, current_user).where(vendor_id: @vendor).page(params[:page]).per_page(9)
	end

	def index
    if params[:search]
      @vendors = Vendor.search(params[:search]).most_followers.paginate(page: params[:page], per_page: 10)
    else
      @vendors = Vendor.most_followers.paginate(page: params[:page], per_page: 10)
    end
  end

  def edit
  	
  end

  def edit_admins
  	@admissions = @vendor.admissions
  end

  def update
  	if @vendor.update_attributes(params[:vendor])
  		flash[:success] = "Profile updated"
  		redirect_to edit_vendor_path(@vendor)
  	else
  		render 'edit'
  	end
  end

	private

		def sort_general
	    %w[recent popular following].include?(params[:sort]) ? params[:sort] : "recent"
	  end

	  def sort_gender
	    %w[Male Female].include?(params[:gender]) ? params[:gender].titleize : "all"
	  end

	  def find_vendor
      @vendor = Vendor.find_by_slug!(params[:id])
    end

    def correct_user
    	@user = @vendor.admissions.find_by_user_id(current_user.id)
    	redirect_to(@vendor) unless @user
    end

end

app/views/vendors/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<!-- BASIC INFO -->
	<h2>Basic information</h2>

	<div class="control-group">
		<%= f.label :name, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :name %>
		</div>
	</div>
	
	<div class="control-group">
		<%= f.label :avatar, "Choose a profile picture", class: "control-label" %>
		<div class="controls edit_user_pic btn btn-default btn-large btn-file" style="background-image:url(<% if @vendor.avatar.present? %><%= @vendor.avatar_url %><% else %><%= asset_path('choose-image.png') %><% end %>);">
			<%= f.file_field :avatar, onchange: "readURL(this);" %>
		</div>
	</div>

	<% unless f.object.new_record? || current_user.avatar.blank? %> 
		<div class="control-group">
			<div class="controls">
				<%= f.label :remove_avatar, class: "checkbox" do %>
					<%= f.check_box :remove_avatar %> 
					Remove profile picture
				<% end %>
			</div>
		</div>
	<% end %>

	<div class="control-group">
		<%= f.label :twitter, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :twitter %>
		</div>
	</div>
	
	<div class="control-group">
		<%= f.label :instagram, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :instagram %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :pinterest, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :pinterest %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :facebook, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :facebook %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :bio, class: "control-label" %>
		<div class="controls">
			<%= f.text_area :bio, rows: 4 %>
		</div>
	</div>

app/views/vendors/_update_nav.html.erb
<ul class="nav nav-list update_user_nav">
	<li class="nav-header">
		<%= link_to @vendor.name, @vendor %>
	</li>
	<li <% if current_page?(controller: 'vendors', action: 'edit') %>class="active"<% end %>>
		<%= link_to "Basic information", edit_vendor_path(@vendor) %>
	</li>
  <li <% if current_page?(controller: 'vendors', action: 'edit_admins') %>class="active"<% end %>>
		<%= link_to "Manage admins", edit_admins_path(@vendor) %>
	</li>
</ul>

app/views/vendors/_vendor.html.erb
<% vendor ||= @vendor %>
<li class="user_info">
	<div class="span8">
  		<%= render partial: 'shared/vendor_info', locals: {:vendor => vendor} %>
  	</div>
</li>

app/views/vendors/edit.html.erb
<% provide(:title, "Edit vendor") %> 

<div class="row">
  <div class="span12">
    <h1 class="edit_profile">Update your profile</h1>
    <hr>
  </div>
</div>
<div class="row">
	<div class="span3 white-box wb-nopadding">
		<%= render 'update_nav' %>
	</div>
  <div class="span9">
    <%= form_for @vendor, html: {class: "form-horizontal"} do |f| %>
      <%= render 'fields', f: f %>

      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save changes", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/vendors/edit_admins.html.erb
<% provide(:title, "Edit vendor") %> 

<div class="row">
  <div class="span12">
    <h1 class="edit_profile">Manage admins</h1>
    <hr>
  </div>
</div>
<div class="row">
	<div class="span3 white-box wb-nopadding">
		<%= render 'update_nav' %>
	</div>
  <div class="span9">
    <h2>Invite admins</h2>
    <p>Invite people to administer this vendor by searching below.</p>
    <%= form_for @vendor.admissions.new do |f| %>
      <%= text_field_tag :invite_to_secret, params[:search], :data => {:provide => "typeahead"}, autocomplete: :off, placeholder: "Type a name." %>
      <%= f.hidden_field :accessible_id %>
      <%= f.hidden_field :accessible_type %>
      <%= f.hidden_field :user_id %>
      <%= f.submit "Add", style: "display:none;" %>
    <% end %>
    <hr>
    <h2>Current admins</h2>
    <div class="row" id="admissions">
      <% @admissions.each do |a| %>
        <% if a.user %>
          <div class="span4" id="<%= a.id if a %>">
            <%= image_tag avatar(a.user, :medium), alt: a.user.name, class: "gravatar gravatar-medium img-rounded" %>
            <strong><%= a.user.name %></strong><br>
            <% if a.user == current_user %>
              This is you.
            <% else %>
              <%= link_to 'Remove admin', a,
                      class: "muted", method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/vendors/index.html.erb
<% provide(:title, 'Find Vendors') %>
<div class="row">
	<div class="span12">
		<h1>Find Vendors</h1>
		<p>Browse, or search below</p>
	</div>
</div>

<div class="row">
	<div class="span9">
		<div>
			<%= form_tag(vendors_path, :method => "get", id: "search-form", class: "form-search form-inline") do %>
				<%= text_field_tag :search, params[:search], class: "span6", placeholder: "Search for vendors" %>
				<%= submit_tag "Search", class: "btn btn-primary" %>
			<% end %>
		</div>

		<div class="row">
			<ul class="users">
				<%= render @vendors %>
			</ul>
			<% if @vendors.empty? %>
				<div class="spacer"></div>
		  	<h2 class="center muted">No vendors found</h2>
		  <% end %>
		</div>

		<%= will_paginate @vendors, page_links: false %>
	</div>
	<aside class="pull-right span3">
		<% if current_user.admin? %>
			<div class="admin">
			  <h3>Admin-info</h3>
			  <span>
			  	<p><%= Vendor.all.count %> vendors in total</p>
			  </span>
			</div>
		<% end %>
		
		<%= render 'shared/aside_facebook' %>
	</aside>
</div>

app/views/vendors/show.html.erb
<% provide(:title, @vendor.name) %>
<div class="row">
  <div class="span12 user_info">
    <div class="row">
      <div class="span9">
        <%= render partial: 'shared/vendor_info', locals: {:vendor => @vendor} %>
      </div>
    	<%= render partial: 'users/follow_stats', locals: {:subject => @vendor} %>
    </div>
  </div>
</div>
<div class="row">
	<div class="span12">
		<ul class="nav nav-pills sort_general pull-left">
			<li><%= sortable_general "popular", true %></li>
		  <li><%= sortable_general "recent", true %></li>		  
		</ul>
		<div class="hidden-phone btn-group sort_gender pull-right">
			<%= sortable_gender "all" %>
			<%= sortable_gender "Male" %>
			<%= sortable_gender "Female" %>
		</div>
	</div>
</div>
<div class="row inspiration">
  <%= render @items %>
</div>

<div id="inspiration-pagination">
  <%= will_paginate @items %>
</div>

app/views/vendors/show.js.erb
$('.inspiration').append('<%= j render(@items) %>');
<% if @items.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@items) %>');
<% else %>
  $('.pagination').remove();
<% end %>